version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./conf/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./conf/nginx/mime.types:/etc/nginx/mime.types
      - ./conf/php-fpm/php-fpm.ini:/etc/php/8.2/fpm/conf.d/90-custom.ini
      - ./www:/var/www